name: snyk container

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '40 18 * * 6'

jobs:
  snyk:
    environment: 
      name: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build --no-cache -t image-to-test .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: image-to-test
        args: --file=Dockerfile --severity-threshold=high
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
